import { useEffect, useState } from "react";
import { Heart, Bookmark, Sparkles } from "lucide-react";
import { recommendOutfits, saveOutfitItems } from "../../../api/outfitApi";
import { useWishlist } from "../../../context/WishlistContext";
import { useToast } from "../../../context/ToastContext";
import "./SuggestedOutfits.css";

// T4.3: displays the new scored-algorithm's complete-outfit suggestions
// (final score %, 5-factor breakdown, color relations, reasons) alongside
// - not replacing - the existing per-category recommendation flow below.
// Anchored on the first selected item, per the T4.1/T4.3 scoping decision.

const FACTOR_LABELS = {
  color: "Color",
  style: "Style",
  pattern: "Pattern",
  occasion: "Occasion",
  season: "Season",
};

const SuggestedOutfits = ({ anchorItem }) => {
  const [outfits, setOutfits] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const { isWishlisted, toggle } = useWishlist();
  const { showToast } = useToast();

  useEffect(() => {
    if (!anchorItem?._id) {
      setOutfits([]);
      return undefined;
    }

    let cancelled = false;

    const fetchOutfits = async () => {
      setLoading(true);
      setError(null);

      try {
        const results = await recommendOutfits(anchorItem._id);
        if (!cancelled) setOutfits(results);
      } catch (err) {
        if (cancelled) return;

        if (err?.response?.status === 503) {
          // Scored recommender disabled (RECOMMENDER=legacy) - nothing to
          // show, not an error state.
          setOutfits([]);
        } else {
          setError("Couldn't load suggested outfits right now.");
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    };

    fetchOutfits();

    return () => {
      cancelled = true;
    };
  }, [anchorItem?._id]);

  const handleLikeClick = async (productId) => {
    if (!localStorage.getItem("token")) {
      showToast("Log in to like items", "error");
      return;
    }
    await toggle(productId);
  };

  const handleSave = async (outfit) => {
    try {
      await saveOutfitItems(outfit.items);
      showToast("Outfit saved to your preferences");
    } catch (err) {
      showToast(
        err?.response?.status === 401 ? "Log in to save outfits" : "Couldn't save this outfit",
        "error"
      );
    }
  };

  if (!anchorItem) return null;
  if (!loading && !error && outfits.length === 0) return null;

  return (
    <section className="suggested-outfits">
      <div className="suggested-outfits-header">
        <span className="selection-step">AI-MATCHED LOOKS</span>
        <h2>
          <Sparkles size={18} />
          Suggested Complete Outfits
        </h2>
        <p>Full outfits generated by a scoring algorithm, built around {anchorItem.name}.</p>
      </div>

      {loading && <div className="suggested-outfits-status">Finding great combinations...</div>}
      {error && <div className="suggested-outfits-status suggested-outfits-error">{error}</div>}

      <div className="suggested-outfits-grid">
        {outfits.map((outfit) => (
          <article className="suggested-outfit-card" key={outfit.items.join("-")}>
            <div className="suggested-outfit-score">{Math.round(outfit.finalScore * 100)}% match</div>

            <div className="suggested-outfit-products">
              {outfit.products.map((product) => (
                <div className="suggested-outfit-product" key={product.id}>
                  <img src={product.image} alt={product.name} />
                  <button
                    type="button"
                    className={`like-button ${isWishlisted?.(product.id) ? "liked" : ""}`}
                    onClick={() => handleLikeClick(product.id)}
                    aria-label={isWishlisted?.(product.id) ? "Unlike" : "Like"}
                  >
                    <Heart size={14} fill={isWishlisted?.(product.id) ? "currentColor" : "none"} />
                  </button>
                  <span>{product.name}</span>
                </div>
              ))}
            </div>

            <div className="suggested-outfit-breakdown">
              {Object.entries(outfit.breakdown).map(([factor, value]) => (
                <div className="breakdown-row" key={factor}>
                  <span className="breakdown-label">{FACTOR_LABELS[factor] || factor}</span>
                  <div className="breakdown-bar-track">
                    <div className="breakdown-bar-fill" style={{ width: `${Math.round(value * 100)}%` }} />
                  </div>
                  <span className="breakdown-value">{Math.round(value * 100)}%</span>
                </div>
              ))}
            </div>

            {outfit.colorRelations?.length > 0 && (
              <div className="suggested-outfit-color-relations">
                {outfit.colorRelations.map(({ pair, relation }) => (
                  <span className="color-relation-badge" key={pair.join("-")}>
                    {relation.replace(/_/g, " ")}
                  </span>
                ))}
              </div>
            )}

            {outfit.reasons?.length > 0 && (
              <ul className="suggested-outfit-reasons">
                {outfit.reasons.map((reason) => (
                  <li key={reason}>{reason}</li>
                ))}
              </ul>
            )}

            <button type="button" className="save-outfit-button" onClick={() => handleSave(outfit)}>
              <Bookmark size={14} />
              Save this outfit
            </button>
          </article>
        ))}
      </div>
    </section>
  );
};

export default SuggestedOutfits;
